name: EPG Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # 每天UTC时间4点运行 (香港时间中午12点)

jobs:
  generate-epg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
        
    - name: Run EPG Generator
      run: python epg_generator.py
      
    - name: Upload EPG file
      uses: actions/upload-artifact@v4
      with:
        name: viu-epg
        path: viu.xml
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull
        git add viu.xml
        git diff-index --quiet HEAD || git commit -m "Automated EPG update: $(date +'%Y-%m-%d %H:%M')"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
